name: "Github Push Action"
author: "Zyrouge"
description: "🚀 Easy to use GitHub Push Action!"
branding:
    icon: "git-merge"
    color: "purple"

inputs:
    github-token:
        description: GitHub token or PAT token
        required: true
        default: ${{ github.token }}
    repository:
        description: "GitHub Repository (format: `username/repo`)"
        required: true
        default: ${{ github.repository }}
    branch:
        description: Repository Branch
        required: true
        default: ${{ github.ref_name }}
    force:
        description: Determines if force push is used
        required: true
        default: false
    directory:
        description: Directory to be pushed
        required: true
        default: "."
    commit-message:
        description: Commit message
        required: true
        default: "[actions] pushed from ${{ github.sha }}"
    local-username:
        description: Git Local Username
        required: true
        default: github-actions
    local-email:
        description: Git Local Email
        required: true
        default: "${{ github.actor }}@users.noreply.github.com"
    verbose:
        description: Verbose logging
        required: true
        default: false
    allow-empty-commit:
        description: Determines if empty commits are allowed
        required: true
        default: false
    skip-fetch:
        description: Allows skipping git fetch
        required: true
        default: false

runs:
    using: node18
    main: dist/index.js
